config/routes.rb
Rails.application.routes.draw do
  # get 'ducks/index'
  # get 'ducks/show'
  # get 'ducks/new'
  # get 'ducks/edit'
  # get 'students/index'
  # get 'students/show'
  # get 'students/new'
  # get 'students/edit'

  resources :ducks
  resources :students

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/duck.rb
class Duck < ApplicationRecord
  belongs_to :student
  # belongs_to :student, required: false

  validates :name, presence: true
  validates :description, presence: true
end

# rails g model student name:string mod:integer
# rails g controller students index show new edit

# rails g model duck name:string description:string student:belongs_to
# rails g controller ducks index show new edit

# rails db:migrate
# rails db:seed

app/models/student.rb
class Student < ApplicationRecord
  has_many :ducks

  validates :name, presence: true
  # validates :mod, :inclusion => 1..10
  validates :mod, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

# Able to log a new student (and make sure that their name is not blank/mod is between 1 and 5)

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ducks_controller.rb
class DucksController < ApplicationController
  def index
    @ducks = Duck.all
  end

  def show
    find_duck
  end

  def new
    @duck = Duck.new
    @students = Student.all
  end

  def create
    Duck.create(duck_params)
    redirect_to ducks_path
  end

  def edit
    find_duck
  end

  def update
    find_duck.update(duck_params)
    redirect_to duck_path(@duck.id)
  end

  private

  def find_duck
    @duck = Duck.find(params[:id])
    # @duck = Duck.find(params[:student_id])
  end

  def duck_params
    params.require(:duck).permit(:name, :description, :student_id)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    find_student
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.create(student_params)

    if @student.valid?
      redirect_to student_path(@student.id)
    else
      flash[:errors] = @student.errors.full_messages
      redirect_to new_student_path
    end
  end

  def edit
    find_student
  end

  def update
    find_student.update(student_params)
    if @student.valid?
      redirect_to student_path(@student.id)
    else
      flash[:errors] = @student.errors.full_messages
      redirect_to new_student_path
    end
  end

  private

  def find_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :mod)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ducks_helper.rb
module DucksHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/ducks/edit.html.erb
<h1>Edit Duck</h1>

<% form_for @duck do |f|%>

  <%= f.label 'Name' %>
  <%= f.text_field :name %>
  <br>
  <%= f.label 'Description' %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

app/views/ducks/index.html.erb
<h1>List of Ducks</h1>

<%= link_to 'Create new duck',  new_duck_path%>

<ul>
  <% @ducks.each do |duck| %>
    <li>
       <%= link_to "#{duck.name}", duck_path(duck.id) %>
    </li>
  <% end %>
</ul>

app/views/ducks/new.html.erb
<h1>Create New Duck</h1>


<%= form_for @duck do |f|%>

  <%= f.label 'Name' %>
  <%= f.text_field :name %>
  <br>
  <%= f.label 'Description' %>
  <%= f.text_field :description %>

  <%= f.label :student_id %>
  <%= f.collection_select :student_id, @students, :id, :name %>

  <%= f.submit %>
<% end %>

app/views/ducks/show.html.erb
<h1>Duck Details</h1>


<h3>Name: <%= @duck.name %>, Description: <%= @duck.description %>, belongs to: <%= link_to "#{@duck.student.name}", student_path(@duck.student.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubberDucking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |error_message| %>
      <li>
        <%= error_message %>
      </li>
    <% end %>
  </ul>
<% end %>


<%= form_for @student do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :mod %>
  <%= f.text_field :mod %>

  <%= f.submit %>
<% end %>

app/views/students/edit.html.erb
<h1>Edit Student Details</h1>


<%= render "form" %>

app/views/students/index.html.erb
<h3> <%= link_to 'Add New Student', new_student_path %> </h3>


<h2>List of Students</h2>


<ul>
  <% @students.each do |student| %>
    <li>
       <%= link_to "#{student.name}", student_path(student.id) %>
    </li>
  <% end %>
</ul>

app/views/students/new.html.erb
<h1>Log New Student</h1>

<%= render "form" %>

app/views/students/show.html.erb
<h1>Student Details</h1>

<h3>Name: <%= @student.name %> in mod <%= @student.mod %></h3>

<p><%= link_to 'Edit Student Details', edit_student_path(@student.id) %></p>

<h5>List of ducks owned by <%= @student.name %>: </h5>

<ul>
  <% @student.ducks.each do |duck| %>
    <li>
       <%= duck.name %>
    </li>
  <% end %>
</ul>